CREATE TABLE CLIENTE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100)
);

CREATE TABLE PRODUTO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    PRECOUNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INTEGER REFERENCES CLIENTE (ID),
    DATA TIMESTAMP,
    VALORTOTAL NUMERIC(20,2)
);

CREATE TABLE ITEMPEDIDO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    IDPEDIDO INTEGER REFERENCES PEDIDO (ID),
    IDPRODUTO INTEGER REFERENCES PRODUTO (ID),
    QUANTIDADE INTEGER
);